name: boardpocket
description: "BoardPocket - Digital Collection & Randomizer for Board Games"
publish_to: 'none'

version: 0.1.1+8

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Database
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^1.1.1
  path: ^1.9.0

  # Storage & Files
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  file_picker: ^8.0.6
  share_plus: ^10.0.0
  permission_handler: ^11.3.1

  # Navigation
  go_router: ^17.1.0

  # State Management
  provider: ^6.1.2

  # Utils
  intl: ^0.20.2
  uuid: ^4.4.2
  collection: ^1.18.0
  shared_preferences: ^2.5.4
  device_info_plus: ^11.4.0
  url_launcher: ^6.3.0

  # Charts
  fl_chart: ^0.70.0
  firebase_analytics: ^12.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  adaptive_icon_background: "#FFFFFF"
  #adaptive_icon_foreground: "assets/icon/ic_launcher_foreground.png"
  min_sdk_android: 21
